// GENERATED BY Scripts/BuildMeshCatalog.py FROM Assets/Meshes/manifest.json. DO NOT EDIT.
//
// Regenerate with `python Scripts/BuildMeshCatalog.py`; `--check` fails when it is stale.
//
// Generated outpost-commander-asset-manifest/1, from the manifest generated 2026-09-22.
//
// EVERY FIGURE HERE IS THE CONTENT'S OWN. ADR-005 never scales a mesh at draw time, so an
// authored extent IS the object's size -- which is why Q37's catalog row is checked against
// this same manifest by Scripts/CheckMeshes.py rather than against this header.
#pragma once

#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>

namespace Outpost
{

/// One row of the delivered mesh set.
///
/// R8: a public aggregate.
struct MeshEntry
{
  std::string_view name;

  /// ADR-021: content ships with the package, so this is a `ms-appx:///` URI and never a path.
  std::wstring_view packageUri;

  std::uint32_t vertexCount = 0;
  std::uint32_t triangleCount = 0;

  /// The file's own bounds, in the file's own coordinates -- Y up, +Z forward.
  float minX = 0.0f;
  float minY = 0.0f;
  float minZ = 0.0f;
  float maxX = 0.0f;
  float maxY = 0.0f;
  float maxZ = 0.0f;

  /// The longest axis, which is what Q37's catalog row states as `sizeUnits`.
  float longestUnits = 0.0f;
};

inline constexpr std::size_t MESH_COUNT = 13;

inline constexpr MeshEntry MESHES[MESH_COUNT] = {
  {.name = "Scout",
   .packageUri = L"ms-appx:///Assets/Meshes/Scout.cmo",
   .vertexCount = 474,
   .triangleCount = 158,
   .minX = -27.0f,
   .minY = -8.0f,
   .minZ = -30.0f,
   .maxX = 27.0f,
   .maxY = 10.0f,
   .maxZ = 30.0f,
   .longestUnits = 60.0f},
  {.name = "Frigate",
   .packageUri = L"ms-appx:///Assets/Meshes/Frigate.cmo",
   .vertexCount = 570,
   .triangleCount = 190,
   .minX = -23.2f,
   .minY = -9.0f,
   .minZ = -45.0f,
   .maxX = 23.2f,
   .maxY = 10.0f,
   .maxZ = 45.0f,
   .longestUnits = 90.0f},
  {.name = "ModuleFrame",
   .packageUri = L"ms-appx:///Assets/Meshes/ModuleFrame.cmo",
   .vertexCount = 744,
   .triangleCount = 248,
   .minX = -41.76f,
   .minY = -9.0f,
   .minZ = -41.11f,
   .maxX = 41.76f,
   .maxY = 9.0f,
   .maxZ = 42.11f,
   .longestUnits = 83.52f},
  {.name = "ModuleShipyardL1",
   .packageUri = L"ms-appx:///Assets/Meshes/ModuleShipyardL1.cmo",
   .vertexCount = 612,
   .triangleCount = 204,
   .minX = -32.19f,
   .minY = -10.0f,
   .minZ = -45.0f,
   .maxX = 32.19f,
   .maxY = 20.0f,
   .maxZ = 45.0f,
   .longestUnits = 90.0f},
  {.name = "ModuleShipyardL2",
   .packageUri = L"ms-appx:///Assets/Meshes/ModuleShipyardL2.cmo",
   .vertexCount = 792,
   .triangleCount = 264,
   .minX = -32.19f,
   .minY = -10.0f,
   .minZ = -45.0f,
   .maxX = 32.19f,
   .maxY = 34.0f,
   .maxZ = 45.0f,
   .longestUnits = 90.0f},
  {.name = "ModuleOreProcessorL1",
   .packageUri = L"ms-appx:///Assets/Meshes/ModuleOreProcessorL1.cmo",
   .vertexCount = 636,
   .triangleCount = 212,
   .minX = -41.35f,
   .minY = -11.0f,
   .minZ = -37.0f,
   .maxX = 37.0f,
   .maxY = 17.0f,
   .maxZ = 39.32f,
   .longestUnits = 78.35f},
  {.name = "ModuleOreProcessorL2",
   .packageUri = L"ms-appx:///Assets/Meshes/ModuleOreProcessorL2.cmo",
   .vertexCount = 804,
   .triangleCount = 268,
   .minX = -43.25f,
   .minY = -11.0f,
   .minZ = -30.0f,
   .maxX = 45.07f,
   .maxY = 17.0f,
   .maxZ = 30.0f,
   .longestUnits = 88.32f},
  {.name = "Station",
   .packageUri = L"ms-appx:///Assets/Meshes/Station.cmo",
   .vertexCount = 1500,
   .triangleCount = 500,
   .minX = -110.0f,
   .minY = -12.0f,
   .minZ = -110.0f,
   .maxX = 110.0f,
   .maxY = 42.0f,
   .maxZ = 110.0f,
   .longestUnits = 220.0f},
  {.name = "AsteroidA",
   .packageUri = L"ms-appx:///Assets/Meshes/AsteroidA.cmo",
   .vertexCount = 378,
   .triangleCount = 126,
   .minX = -31.23f,
   .minY = -22.62f,
   .minZ = -29.88f,
   .maxX = 31.21f,
   .maxY = 22.62f,
   .maxZ = 29.64f,
   .longestUnits = 62.44f},
  {.name = "AsteroidB",
   .packageUri = L"ms-appx:///Assets/Meshes/AsteroidB.cmo",
   .vertexCount = 378,
   .triangleCount = 126,
   .minX = -38.52f,
   .minY = -30.3f,
   .minZ = -38.83f,
   .maxX = 43.97f,
   .maxY = 30.3f,
   .maxZ = 38.33f,
   .longestUnits = 82.49f},
  {.name = "AsteroidC",
   .packageUri = L"ms-appx:///Assets/Meshes/AsteroidC.cmo",
   .vertexCount = 378,
   .triangleCount = 126,
   .minX = -51.49f,
   .minY = -40.8f,
   .minZ = -46.92f,
   .maxX = 59.63f,
   .maxY = 40.8f,
   .maxZ = 46.62f,
   .longestUnits = 111.12f},
  {.name = "AsteroidD",
   .packageUri = L"ms-appx:///Assets/Meshes/AsteroidD.cmo",
   .vertexCount = 378,
   .triangleCount = 126,
   .minX = -66.77f,
   .minY = -48.27f,
   .minZ = -69.41f,
   .maxX = 55.29f,
   .maxY = 48.27f,
   .maxZ = 58.46f,
   .longestUnits = 127.87f},
  {.name = "AsteroidE",
   .packageUri = L"ms-appx:///Assets/Meshes/AsteroidE.cmo",
   .vertexCount = 378,
   .triangleCount = 126,
   .minX = -90.91f,
   .minY = -70.68f,
   .minZ = -71.09f,
   .maxX = 75.97f,
   .maxY = 70.68f,
   .maxZ = 69.69f,
   .longestUnits = 166.88f},
};

/// The hull palette, as shader constants. The vertex colour's G channel indexes it:
/// 0 is DEEP, 128 is BASE, 255 is EDGE (`manifest.json`'s vertexColorConvention).
inline constexpr float HULL_PALETTE[3][3] = {
  {0.10588235294117647f, 0.12941176470588237f, 0.16470588235294117f}, // DEEP #1B212A
  {0.2549019607843137f, 0.29411764705882354f, 0.34509803921568627f}, // BASE #414B58
  {0.5098039215686274f, 0.5568627450980392f, 0.611764705882353f}, // EDGE #828E9C
};

/// The four team colours, in player order. The vertex colour's R channel selects between the
/// hull palette above and the owning player's colour here -- which is what lets one instanced
/// draw cover every ship of a shape regardless of owner.
inline constexpr float TEAM_PALETTE[4][3] = {
  {0.2196078431372549f, 0.8196078431372549f, 0.9607843137254902f}, // OWN #38D1F5
  {0.7686274509803922f, 0.9098039215686274f, 0.2196078431372549f}, // B #C4E838
  {0.9686274509803922f, 0.37254901960784315f, 0.8156862745098039f}, // C #F75FD0
  {0.6431372549019608f, 0.3607843137254902f, 1.0f}, // D #A45CFF
};

/// ADR-019's ceiling is stated against this: the backdrop the hulls are read against.
inline constexpr float BACKDROP[3] = {0.01568627450980392f, 0.023529411764705882f, 0.0392156862745098f}; // #04060A

/// The light rig the plates were authored under. **It is the handoff's decision and not the
/// design's** -- the design states no rig, the plates needed one, and a rig that is not written
/// down makes the plates unreproducible.
inline constexpr float KEY_LIGHT_DIRECTION[3] = {-0.42f, 0.8f, 0.38f};
inline constexpr float KEY_LIGHT_INTENSITY = 0.85f;
inline constexpr float FILL_LIGHT_DIRECTION[3] = {0.55f, -0.22f, -0.62f};
inline constexpr float FILL_LIGHT_INTENSITY = 0.16f;
inline constexpr float AMBIENT_COLOR[3] = {0.2f, 0.25098039215686274f, 0.3215686274509804f};
inline constexpr float AMBIENT_INTENSITY = 0.7f;

/// The row a name identifies, or nullptr. Linear over thirteen entries, which is nothing.
[[nodiscard]] constexpr const MeshEntry* FindMesh(std::string_view _name) noexcept
{
  for (const MeshEntry& entry : MESHES)
  {
    if (entry.name == _name)
    {
      return &entry;
    }
  }
  return nullptr;
}

} // namespace Outpost
