#!/usr/bin/env python3
"""Regenerate GameClient/MeshCatalog.g.h from manifest.json.

The handoff shipped a MeshCatalog.g.h and it was dropped when its item groups were folded into the
project, so nothing carried the names, the package URIs, the counts, the extents or the hull palette
into the client. This is what puts them back, and it generates rather than transcribes for the
reason every generated file exists: manifest.json ships beside the meshes, so the runtime asserts
against the same file the build validated.

    python Scripts/BuildMeshCatalog.py            # write it
    python Scripts/BuildMeshCatalog.py --check    # fail if it is stale, which is what CI wants

WHAT IS AND IS NOT IN HERE. The names, the URIs, the counts, the extents and the palette are facts
about the content and belong to whatever read the manifest. Which hull draws which mesh is a GAME
fact (R9) and lives in GameClient/HullMesh.cpp, written by hand, because a generator that knew a
Scout was a hull would be the manifest deciding the catalog.
"""
import argparse
import io
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(REPO_ROOT, "OutpostCommander", "Assets", "Meshes", "manifest.json")
OUTPUT = os.path.join(REPO_ROOT, "GameClient", "MeshCatalog.g.h")


def rgb(hex_string):
    """#RRGGBB to three floats, linearized the way a shader constant wants them."""
    value = hex_string.lstrip("#")
    return tuple(int(value[i:i + 2], 16) / 255.0 for i in (0, 2, 4))


def flt(value):
    """A C++ float literal.

    `%g` alone writes 45 for a whole number and `45f` is not a literal -- MSVC calls it an invalid
    literal suffix, which is a confusing way to be told about a missing decimal point.
    """
    text = repr(float(value))
    if ("." not in text) and ("e" not in text) and ("E" not in text):
        text += ".0"
    return text + "f"


def generate(manifest):
    out = io.StringIO()
    w = out.write

    w("// GENERATED BY Scripts/BuildMeshCatalog.py FROM Assets/Meshes/manifest.json. DO NOT EDIT.\n")
    w("//\n")
    w("// Regenerate with `python Scripts/BuildMeshCatalog.py`; `--check` fails when it is stale.\n")
    w("//\n")
    w("// Generated %s, from the manifest generated %s.\n" % (manifest["format"], manifest["generated"]))
    w("//\n")
    w("// EVERY FIGURE HERE IS THE CONTENT'S OWN. ADR-005 never scales a mesh at draw time, so an\n")
    w("// authored extent IS the object's size -- which is why Q37's catalog row is checked against\n")
    w("// this same manifest by Scripts/CheckMeshes.py rather than against this header.\n")
    w("//\n")
    w("// The format gate walks every tracked header, and no generated header will ever satisfy a\n")
    w("// style -- a colour channel carries sixteen digits and the hex it came from, and the two\n")
    w("// together overrun any column limit worth having. NeuronClient/CompiledShader/ answers the\n")
    w("// same problem with a directory .clang-format; this file cannot, because GameClient/ also\n")
    w("// holds hand-written code that must stay formatted. So the exemption is file-scoped, and\n")
    w("// there is deliberately no `clang-format on` below it -- the whole file is generated.\n")
    w("// clang-format off\n")
    w("#pragma once\n\n")
    w("#include <cstddef>\n#include <cstdint>\n#include <span>\n#include <string_view>\n\n")
    w("namespace Outpost\n{\n\n")

    w("/// One row of the delivered mesh set.\n")
    w("///\n")
    w("/// R8: a public aggregate.\n")
    w("struct MeshEntry\n{\n")
    w("  std::string_view name;\n\n")
    w("  /// ADR-021: content ships with the package, so this is a `ms-appx:///` URI and never a path.\n")
    w("  std::wstring_view packageUri;\n\n")
    w("  std::uint32_t vertexCount = 0;\n")
    w("  std::uint32_t triangleCount = 0;\n\n")
    w("  /// The file's own bounds, in the file's own coordinates -- Y up, +Z forward.\n")
    w("  float minX = 0.0f;\n  float minY = 0.0f;\n  float minZ = 0.0f;\n")
    w("  float maxX = 0.0f;\n  float maxY = 0.0f;\n  float maxZ = 0.0f;\n\n")
    w("  /// The longest axis, which is what Q37's catalog row states as `sizeUnits`.\n")
    w("  float longestUnits = 0.0f;\n};\n\n")

    meshes = manifest["meshes"]
    w("inline constexpr std::size_t MESH_COUNT = %d;\n\n" % len(meshes))

    w("inline constexpr MeshEntry MESHES[MESH_COUNT] = {\n")
    for m in meshes:
        e = m["extents"]
        w("  {.name = \"%s\",\n" % m["name"])
        w("   .packageUri = L\"ms-appx:///Assets/Meshes/%s.cmo\",\n" % m["name"])
        w("   .vertexCount = %d,\n" % m["vertices"])
        w("   .triangleCount = %d,\n" % m["triangles"])
        w("   .minX = %s,\n   .minY = %s,\n   .minZ = %s,\n" % tuple(flt(v) for v in e["min"]))
        w("   .maxX = %s,\n   .maxY = %s,\n   .maxZ = %s,\n" % tuple(flt(v) for v in e["max"]))
        w("   .longestUnits = %s},\n" % flt(e["longest"]))
    w("};\n\n")

    w("/// The hull palette, as shader constants. The vertex colour's G channel indexes it:\n")
    w("/// 0 is DEEP, 128 is BASE, 255 is EDGE (`manifest.json`'s vertexColorConvention).\n")
    w("inline constexpr float HULL_PALETTE[3][3] = {\n")
    for key in ("DEEP", "BASE", "EDGE"):
        w("  {%s, %s, %s}, // %s %s\n"
          % (tuple(flt(c) for c in rgb(manifest["palette"]["hull"][key]))
             + (key, manifest["palette"]["hull"][key])))
    w("};\n\n")

    w("/// The four team colours, in player order. The vertex colour's R channel selects between the\n")
    w("/// hull palette above and the owning player's colour here -- which is what lets one instanced\n")
    w("/// draw cover every ship of a shape regardless of owner.\n")
    w("inline constexpr float TEAM_PALETTE[4][3] = {\n")
    for key in ("OWN", "B", "C", "D"):
        w("  {%s, %s, %s}, // %s %s\n"
          % (tuple(flt(c) for c in rgb(manifest["palette"]["team"][key]))
             + (key, manifest["palette"]["team"][key])))
    w("};\n\n")

    w("/// ADR-019's ceiling is stated against this: the backdrop the hulls are read against.\n")
    w("inline constexpr float BACKDROP[3] = {%s, %s, %s}; // %s\n\n"
      % (tuple(flt(c) for c in rgb(manifest["palette"]["backdrop"]))
         + (manifest["palette"]["backdrop"],)))

    light = manifest["light"]
    w("/// The light rig the plates were authored under. **It is the handoff's decision and not the\n")
    w("/// design's** -- the design states no rig, the plates needed one, and a rig that is not written\n")
    w("/// down makes the plates unreproducible.\n")
    w("inline constexpr float KEY_LIGHT_DIRECTION[3] = {%s, %s, %s};\n" % tuple(flt(v) for v in light["key"]["direction"]))
    w("inline constexpr float KEY_LIGHT_INTENSITY = %s;\n" % flt(light["key"]["intensity"]))
    w("inline constexpr float FILL_LIGHT_DIRECTION[3] = {%s, %s, %s};\n" % tuple(flt(v) for v in light["fill"]["direction"]))
    w("inline constexpr float FILL_LIGHT_INTENSITY = %s;\n" % flt(light["fill"]["intensity"]))
    w("inline constexpr float AMBIENT_COLOR[3] = {%s, %s, %s};\n" % tuple(flt(c) for c in rgb(light["ambient"]["hex"])))
    w("inline constexpr float AMBIENT_INTENSITY = %s;\n\n" % flt(light["ambient"]["intensity"]))

    w("/// The row a name identifies, or nullptr. Linear over thirteen entries, which is nothing.\n")
    w("[[nodiscard]] constexpr const MeshEntry* FindMesh(std::string_view _name) noexcept\n{\n")
    w("  for (const MeshEntry& entry : MESHES)\n  {\n")
    w("    if (entry.name == _name)\n    {\n      return &entry;\n    }\n  }\n")
    w("  return nullptr;\n}\n\n")

    w("} // namespace Outpost\n")
    return out.getvalue()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", default=MANIFEST)
    ap.add_argument("--output", default=OUTPUT)
    ap.add_argument("--check", action="store_true", help="fail when the file on disk is stale")
    args = ap.parse_args()

    with io.open(args.manifest, "r", encoding="utf-8") as fh:
        manifest = json.load(fh)

    generated = generate(manifest)

    if args.check:
        try:
            with io.open(args.output, "r", encoding="utf-8", newline="") as fh:
                existing = fh.read()
        except OSError:
            sys.stderr.write("BuildMeshCatalog: %s does not exist\n" % args.output)
            return 1
        if existing.replace("\r\n", "\n") != generated:
            sys.stderr.write("BuildMeshCatalog: %s is stale; run Scripts/BuildMeshCatalog.py\n" % args.output)
            return 1
        print("BuildMeshCatalog: %s is current, %d meshes" % (os.path.basename(args.output), len(manifest["meshes"])))
        return 0

    with io.open(args.output, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(generated)
    print("BuildMeshCatalog: wrote %s, %d meshes" % (os.path.basename(args.output), len(manifest["meshes"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
