#!/usr/bin/env python3
"""Write Tools/FractalTable.py: the two fixed-point tables the landscape generator reads.

    python3 Tools/GenerateFractalTable.py

Run once and commit the output. This is the only place float arithmetic touches the landscape:
the generator (Tools/LandscapeTool.py and its C++ port in Sim) reads the committed integers and
never recomputes them, so that two machines with different libm implementations generate the
same heights (AGENTS.md R16; TechnicalDesign.md §4.4).

FALLOFF_16_16[fd] for a fractal dimension fd in hundredths is round(2^(-fd/100) * 65536): the
factor the noise amplitude is multiplied by from one subdivision level to the next. Species
computes (10 * length)^fd per point with length halving per level, which is the same falloff
of 2^fd per level; the constant in front is absorbed into the recipe's amplitude.

LOWLAND_POWER_16_16[s][x] for a lowland-smoothing exponent s in hundredths and an absolute raw
height x in whole units (0..255, clamped above) is round(x^(s/100) * 65536): the Species term
|base|^lowlandSmoothingFactor that makes noise near sea level an order of magnitude smaller than
noise on high ground.
"""
from __future__ import annotations

from pathlib import Path

FD_MIN, FD_MAX = 100, 400
LOWLAND_EXPONENTS = (70, 80, 87, 100)
HEIGHT_ENTRIES = 256


def main() -> None:
    falloff = [round(2.0 ** (-fd / 100.0) * 65536) for fd in range(FD_MIN, FD_MAX + 1)]
    power = {s: [round((x ** (s / 100.0)) * 65536) for x in range(HEIGHT_ENTRIES)] for s in LOWLAND_EXPONENTS}

    lines = [
        '"""Fixed-point tables for the landscape generator. GENERATED by Tools/GenerateFractalTable.py;',
        'do not edit. See that script for what each table is."""',
        "",
        f"FD_MIN = {FD_MIN}",
        f"FD_MAX = {FD_MAX}",
        f"LOWLAND_EXPONENTS = {LOWLAND_EXPONENTS}",
        f"HEIGHT_ENTRIES = {HEIGHT_ENTRIES}",
        "",
        "# FALLOFF_16_16[fd - FD_MIN] = round(2^(-fd/100) * 65536)",
        "FALLOFF_16_16 = [",
    ]
    for start in range(0, len(falloff), 12):
        lines.append("    " + ", ".join(str(v) for v in falloff[start : start + 12]) + ",")
    lines.append("]")
    lines.append("")
    lines.append("# LOWLAND_POWER_16_16[s][x] = round(x^(s/100) * 65536), x in whole units clamped to HEIGHT_ENTRIES - 1")
    lines.append("LOWLAND_POWER_16_16 = {")
    for s in LOWLAND_EXPONENTS:
        lines.append(f"    {s}: [")
        for start in range(0, HEIGHT_ENTRIES, 12):
            lines.append("        " + ", ".join(str(v) for v in power[s][start : start + 12]) + ",")
        lines.append("    ],")
    lines.append("}")
    lines.append("")
    Path(__file__).with_name("FractalTable.py").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote FractalTable.py: {len(falloff)} falloff entries, {len(LOWLAND_EXPONENTS)} x {HEIGHT_ENTRIES} lowland entries")


if __name__ == "__main__":
    main()
