#!/usr/bin/env python3
"""Write NeuronCore/SinTable.h: the 1,024-entry sine table of NeuronCore/BinaryAngle.h in 16.16 fixed point.

    python3 Tools/GenerateSinTable.py

Run once and commit the output. A binary angle is a std::uint16_t turn (65,536 per revolution,
TechnicalDesign.md §4.1); the table holds sin(2*pi*i/1024) for i in 0..1023 as
round(sin(...) * 65536), and BinaryAngle.cpp reads it with linear interpolation between entries.
This script is the only place float touches the table, so that every machine's simulation adds
the same integers (AGENTS.md R16).
"""
from __future__ import annotations

import math
from pathlib import Path

ENTRIES = 1024
ONE = 65536


def main() -> None:
    values = [round(math.sin(2.0 * math.pi * i / ENTRIES) * ONE) for i in range(ENTRIES)]
    lines = [
        "// NeuronCore/SinTable.h -- GENERATED by `python3 Tools/GenerateSinTable.py`; do not edit.",
        "// sin(2*pi*i/1024) in 16.16 fixed point for i in 0..1023; BinaryAngle.cpp interpolates between",
        "// entries. The generator is the only place float touches this table (AGENTS.md R16).",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace Neuron",
        "{",
        "",
        f"inline constexpr std::array<std::int32_t, {ENTRIES}> SIN_TABLE_16_16 = {{",
    ]
    for start in range(0, ENTRIES, 8):
        lines.append("  " + ", ".join(f"{v:6d}" for v in values[start : start + 8]) + ",")
    lines.append("};")
    lines.append("")
    lines.append("} // namespace Neuron")
    Path(__file__).resolve().parent.parent.joinpath("Core", "SinTable.h").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote NeuronCore/SinTable.h: {ENTRIES} entries")


if __name__ == "__main__":
    main()
